### ISSUE TITLE
Ability to delete Milestones in the same way that labels can be (as advertised)

### ISSUE THREAD

**Issue by chandadharap** [strongloop-internal/github-tools#8]

**Comment by bajtos** [comment]
Is it a good idea to delete milestones? Why can't we close them instead? (That's what is currently implemented.)

**Comment by chandadharap** [comment]
Milestones in our case are Epics simply because Waffle/github does not support Epics. And yes Epics should be deleted when finished. The list can become endless.

- Chanda

**Comment by rmg** [comment]
Closed milestones are displayed separately from open milestones. This is the same way issues and pull requests work. Is there somewhere that is displaying this endless list? Having records of when milestones are started and when they are closed would be useful for reporting.

Actually, milestones would probably be a good way of modelling sprints for that reason. They even have progress bars based on opened/closed issues under them.. Are we using labels for sprints mainly because that's how waffle was implemented when we started? Labels would be much better for ephemeral attributes like issue state (to review, TBR, released, "current sprint", "next sprint", etc.) than association with fixed/persistent things like specific sprints and milestones.

**Comment by sam-github** [comment]
I agree on milestones for sprints, seems a better model. Maybe waffle can have it pointed out to them, but they aren't a sprint thingy, they are kanban, possibly why they did not consider milestones for columns.

As for deleting milestones... there are 4 promisify milestones, with different spellings, we don't need them all for historical interest... maybe closing is good in general, but deleting is nice sometimes, too.
